services:
  redis:
    image: redis:7-alpine
    container_name: leaderboard-go-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    container_name: leaderboard-go-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-leaderboard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-leaderboard}
      POSTGRES_DB: ${POSTGRES_DB:-leaderboard}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redisdata:
  pgdata:
